image: debian:bookworm

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/lyriarte/cm7b5:latest

before_script:
  - apt-get update && apt-get install -y gcc flex bison make yasm

build:
  stage: build
  script:
    - make
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  
  artifacts:
    paths:
      - compiler

test:
  stage: test
  script:
    - echo "Iterative fibonacci"
    - cat fib1.c | ./compiler > fib1.asm
    - test "$(md5sum fib1.asm)" = "5d651d5afe1ca87af7633e570bec1aac  fib1.asm"
    - yasm -f elf fib1.asm
    - ld -m elf_i386 -s -o fib1.bin fib1.o
    - test "$(./fib1.bin)" = "00000008"
    - echo "Recursive fibonacci"
    - cat fib2.c | ./compiler > fib2.asm
    - test "$(md5sum fib2.asm)" = "0c09744dfffc7fa49336d7c16759ecde  fib2.asm"
    - yasm -f elf fib2.asm
    - ld -m elf_i386 -s -o fib2.bin fib2.o
    - test "$(./fib2.bin)" = "00000008"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  
  artifacts:
    paths:
      - fib1.asm
      - fib1.bin
      - fib2.asm
      - fib2.bin

publish:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main

